[package]
name = "mitsuba"
version = "1.0.0"
authors = ["moot"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
env_logger = "0.8.3"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6.4", features = ["full"] }
diesel = { version = "1.4.6", features = ["postgres", "numeric", "64-column-tables", "r2d2"] }
dotenv = "0.15.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
nonzero_ext = "0.2.0"
anyhow = "1.0.38"
lazy_static = "1.4.0"
governor = "0.3.2"
bytes = "1.0.1"
backoff = { version = "0.3.0", features = ["tokio"] }
instant = "0.1.9"
regex = "1"
base64 = "0.13.0"
base32 = "0.4.0"
actix-web = "4.0.0-BETA.4"
actix-files = "0.6.0-beta.3"
diesel_migrations = "1.4.0"
clap = "3.0.0-beta.2"
handlebars = { version = "3.0.0", features = ["dir_source"] }
unicode-truncate = "0.2.0"
handlebars_misc_helpers = "0.11.2"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3