# Configured to work with Traefik proxy

version: '3.8'

services:

  server:
    image: ghcr.io/mitsuba-dev/mitsuba:latest
    hostname: mitsuba
    labels:
        # Prometheus
        - "prometheus-job=mitsuba"
        - "prometheus-port=9000"
        # Traefik
        - "traefik.enable=true"
        # Router
        - "traefik.http.routers.mitsuba.rule=Host(`${HOSTNAME}`)"
        - "traefik.http.routers.mitsuba.entrypoints=websecure"
        - "traefik.http.routers.mitsuba.tls=true"
        - "traefik.http.routers.mitsuba.service=mitsuba-service"
        # Service
        - "traefik.http.services.mitsuba-service.loadbalancer.server.port=8080"
        - "traefik.http.services.mitsuba-service.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.mitsuba-service.loadbalancer.sticky.cookie.secure=true"
    environment:
      - DATABASE_URL=postgresql://mitsuba:${POSTGRESQL_PASSWORD}@postgresql/mitsuba
      - ENABLE_S3_STORAGE=true
      - S3_ACCESS_KEY_ID=${S3_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_KEY}
      - S3_BUCKET=${S3_BUCKET_NAME}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_REGION=${S3_REGION}
      - PROMETHEUS_PORT=9000
      - RUST_BACKTRACE=1
      - RUST_LOG=mitsuba=info

  postgresql:
    image: postgres:14-alpine
    hostname: postgresql
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mitsuba
      - POSTGRES_USER=mitsuba
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
 
volumes:
  database:   
